language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_script:
  - cd board/


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


notifications:
  email:
    recipients:
      - min9288@gmail.com
