language: java
jdk:
  - openjdk11

branches:
  only:
    - main

before_install:
  - chmod +x gradlew

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r Member_Board_REST-API *
  - mkdir -p deploy
  - mv Member_Board_REST-API.zip deploy/Member_Board_REST-API.zip


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: member-board-service-deploy
    region: ap-northeast-2
    cleanup: false
    acl: public_read
    local_dir: deploy
    wait-until-deployed: true
    on:
      repo: min9288/Member_Board_REST-API
      branch: main

notifications:
  email:
    recipients:
      - min9288@gmail.com