version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/nonstop/Member_Board_REST-API/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 777

hooks:
  AfterInstall:
    - location: execute-deploy.sh
      timeout: 180
      runas: root
