server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://db-b11aq.pub-cdb.ntruss.com:3306/boardServiceDB
    username: boardUser
    password: qwer@1234

  jpa:
    hibernate:
      ddl-auto: update

  jwt:
    secretKey: qwer1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: khtest9288@gmail.com
    password: binqhczjdssuepnx
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
